/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tree.glb 
Author: gashtan (https://sketchfab.com/gashtan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/evergreen-tree-7abb385ee43343ab89bc7789d8afe1b1
Title: evergreen tree
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.auto_1} position={[-8.869, -8.869, 0]} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.auto} position={[-52.703, -52.567, 32.894]} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
